#!/usr/bin/env zsh
set -euo pipefail

usage() {
  cat <<'EOF'
Generate a founder update post package from scoreboard + weekly delta markdown.

Usage:
  zsh scripts/generate_founder_update_post.sh [options]

Required:
  --scoreboard <path>     Scoreboard markdown generated by generate_founder_scoreboard.sh
  --delta <path>          Delta markdown generated by generate_founder_weekly_delta.sh
  --out <path>            Output markdown path

Optional:
  --week <label>          Week label override (default: inferred from scoreboard heading)
  --product <text>        Product name (default: Fluid Reader)
  --primary-channel <text> Primary post channel label (default: X / Threads)
  --backup-channel <text>  Backup post channel label (default: LinkedIn)
  --cta <text>            Call-to-action line
  -h, --help              Show help

Example:
  zsh scripts/generate_founder_update_post.sh \
    --scoreboard .build/founder/scoreboard.md \
    --delta .build/founder/weekly-delta-2026-W23.md \
    --out .build/founder/founder-update-2026-W23.md
EOF
}

scoreboard_path=""
delta_path=""
output_path=""
week_label=""
product_name="Fluid Reader"
primary_channel="X / Threads"
backup_channel="LinkedIn"
cta_text="If you're building, reply with your KPI bottleneck and I'll share the exact command flow."

while (( $# > 0 )); do
  case "$1" in
    --scoreboard)
      scoreboard_path="${2:-}"
      shift 2
      ;;
    --delta)
      delta_path="${2:-}"
      shift 2
      ;;
    --out)
      output_path="${2:-}"
      shift 2
      ;;
    --week)
      week_label="${2:-}"
      shift 2
      ;;
    --product)
      product_name="${2:-}"
      shift 2
      ;;
    --primary-channel)
      primary_channel="${2:-}"
      shift 2
      ;;
    --backup-channel)
      backup_channel="${2:-}"
      shift 2
      ;;
    --cta)
      cta_text="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

for pair in \
  "scoreboard_path:$scoreboard_path" \
  "delta_path:$delta_path" \
  "output_path:$output_path"; do
  key="${pair%%:*}"
  value="${pair#*:}"
  if [[ -z "$value" ]]; then
    echo "Missing required option: $key" >&2
    usage >&2
    exit 1
  fi
done

if [[ ! -f "$scoreboard_path" ]]; then
  echo "Scoreboard file not found: $scoreboard_path" >&2
  exit 1
fi
if [[ ! -f "$delta_path" ]]; then
  echo "Delta file not found: $delta_path" >&2
  exit 1
fi

trim() {
  echo "$1" | sed -E 's/^ +| +$//g'
}

extract_heading_suffix() {
  local file="$1"
  local prefix="$2"
  local label
  label="$(sed -n "s/^# ${prefix} - //p" "$file" | head -n 1)"
  if [[ -z "$label" ]]; then
    echo "n/a"
  else
    echo "$label"
  fi
}

extract_snapshot_value() {
  local file="$1"
  local key="$2"
  local line
  line="$(grep -E "^- ${key}:" "$file" | head -n 1 || true)"
  if [[ -z "$line" ]]; then
    echo "n/a"
    return
  fi
  trim "$(echo "$line" | sed -E "s/^- ${key}: *//")"
}

extract_metric_row() {
  local file="$1"
  local metric="$2"
  awk -F'|' -v metric="$metric" '
    function clean(value) {
      gsub(/^[ \t]+|[ \t]+$/, "", value)
      return value
    }
    $0 ~ /^\|/ {
      key = clean($2)
      if (key == metric) {
        target = clean($3)
        actual = clean($4)
        delta = clean($5)
        status = clean($6)
        direction = clean($7)
        print target "\t" actual "\t" delta "\t" status "\t" direction
        exit
      }
    }
  ' "$file"
}

extract_signal_line() {
  local file="$1"
  local index="$2"
  awk -v idx="$index" '
    /^## Signals/ { in_signals=1; next }
    in_signals && /^## / { in_signals=0 }
    in_signals && /^- / {
      count++
      if (count == idx) {
        sub(/^- /, "", $0)
        print $0
        exit
      }
    }
  ' "$file"
}

score_heading="$(extract_heading_suffix "$scoreboard_path" "Founder KPI Scoreboard")"
delta_heading="$(extract_heading_suffix "$delta_path" "Founder Weekly Delta")"
if [[ -z "$week_label" ]]; then
  week_label="$score_heading"
fi
if [[ "$week_label" == "n/a" || -z "$week_label" ]]; then
  week_label="$(date '+%Y-W%V')"
fi

on_track="$(extract_snapshot_value "$scoreboard_path" "On Track")"
at_risk="$(extract_snapshot_value "$scoreboard_path" "At Risk")"
off_track="$(extract_snapshot_value "$scoreboard_path" "Off Track")"
summary="$(extract_snapshot_value "$scoreboard_path" "Summary")"

mrr_row="$(extract_metric_row "$scoreboard_path" "MRR")"
cac_row="$(extract_metric_row "$scoreboard_path" "CAC")"
ltv_cac_row="$(extract_metric_row "$scoreboard_path" "LTV/CAC")"

if [[ -z "$mrr_row" ]]; then mrr_row=$'n/a\tn/a\tn/a\tn/a\tn/a'; fi
if [[ -z "$cac_row" ]]; then cac_row=$'n/a\tn/a\tn/a\tn/a\tn/a'; fi
if [[ -z "$ltv_cac_row" ]]; then ltv_cac_row=$'n/a\tn/a\tn/a\tn/a\tn/a'; fi

IFS=$'\t' read -r mrr_target mrr_actual mrr_delta mrr_status _ <<< "$mrr_row"
IFS=$'\t' read -r cac_target cac_actual cac_delta cac_status _ <<< "$cac_row"
IFS=$'\t' read -r ltv_cac_target ltv_cac_actual ltv_cac_delta ltv_cac_status _ <<< "$ltv_cac_row"

signal_1="$(extract_signal_line "$delta_path" 1)"
signal_2="$(extract_signal_line "$delta_path" 2)"
if [[ -z "$signal_1" ]]; then signal_1="Key signals unavailable. Re-run weekly delta report."; fi
if [[ -z "$signal_2" ]]; then signal_2="Use the scoreboard to focus next actions."; fi

generated_on="$(date '+%Y-%m-%d %H:%M:%S %Z')"

mkdir -p "$(dirname "$output_path")"

cat > "$output_path" <<EOF
# Founder Update Post Pack - ${week_label}

Generated: ${generated_on}
Product: ${product_name}
Source scoreboard: ${score_heading}
Source delta: ${delta_heading}

## KPI Snapshot

- Scoreboard status: ${on_track} on track / ${at_risk} at risk / ${off_track} off track
- Weekly summary: ${summary}
- MRR: ${mrr_actual} (target ${mrr_target}, delta ${mrr_delta}, status ${mrr_status})
- CAC: ${cac_actual} (target ${cac_target}, delta ${cac_delta}, status ${cac_status})
- LTV/CAC: ${ltv_cac_actual} (target ${ltv_cac_target}, delta ${ltv_cac_delta}, status ${ltv_cac_status})

## Primary Post Draft (${primary_channel})

\`\`\`text
Founder update (${week_label}) for ${product_name}:

- Scoreboard: ${on_track} on track / ${at_risk} at risk / ${off_track} off track
- MRR: ${mrr_actual} (${mrr_delta} vs target)
- CAC: ${cac_actual} (${cac_delta} vs target)
- LTV/CAC: ${ltv_cac_actual} (${ltv_cac_delta} vs target)

Signals:
- ${signal_1}
- ${signal_2}

${cta_text}
\`\`\`

## Backup Post Draft (${backup_channel})

\`\`\`text
Weekly founder KPI review (${week_label}):

Current scoreboard:
- On track: ${on_track}
- At risk: ${at_risk}
- Off track: ${off_track}

Metric highlights:
- MRR: ${mrr_actual} (target ${mrr_target})
- CAC: ${cac_actual} (target ${cac_target})
- LTV/CAC: ${ltv_cac_actual} (target ${ltv_cac_target})

This week’s focus: ${summary}
\`\`\`

## Comment Reply Seeds

- "What moved most this week?" -> ${signal_1}
- "What are you fixing next?" -> ${signal_2}
- "How are you measuring it?" -> We run weekly review + delta + scoreboard scripts and then ship one focused experiment.
EOF

echo "Wrote founder update post pack: $output_path"
