#!/usr/bin/env zsh
set -euo pipefail

usage() {
  cat <<'EOF'
Generate a founder week-over-week KPI delta markdown file.

Usage:
  zsh scripts/generate_founder_weekly_delta.sh [options]

Required options:
  --previous <path>      Previous review markdown generated by founder weekly review script
  --current <path>       Current review markdown generated by founder weekly review script
  --out <path>           Output markdown path

Optional:
  --label-prev <text>    Override previous period label
  --label-current <text> Override current period label
  -h, --help             Show help

Example:
  zsh scripts/generate_founder_weekly_delta.sh \
    --previous .build/founder/weekly-review-2026-W22.md \
    --current .build/founder/weekly-review-2026-W23.md \
    --out .build/founder/weekly-delta-2026-W23.md
EOF
}

previous_path=""
current_path=""
output_path=""
label_prev=""
label_current=""

while (( $# > 0 )); do
  case "$1" in
    --previous)
      previous_path="${2:-}"
      shift 2
      ;;
    --current)
      current_path="${2:-}"
      shift 2
      ;;
    --out)
      output_path="${2:-}"
      shift 2
      ;;
    --label-prev)
      label_prev="${2:-}"
      shift 2
      ;;
    --label-current)
      label_current="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

for pair in \
  "previous_path:$previous_path" \
  "current_path:$current_path" \
  "output_path:$output_path"; do
  key="${pair%%:*}"
  value="${pair#*:}"
  if [[ -z "$value" ]]; then
    echo "Missing required option: $key" >&2
    usage >&2
    exit 1
  fi
done

if [[ ! -f "$previous_path" ]]; then
  echo "Previous review file not found: $previous_path" >&2
  exit 1
fi
if [[ ! -f "$current_path" ]]; then
  echo "Current review file not found: $current_path" >&2
  exit 1
fi

extract_heading_label() {
  local file="$1"
  local label
  label="$(sed -n 's/^# Founder Weekly Review - //p' "$file" | head -n 1)"
  if [[ -z "$label" ]]; then
    echo "$(basename "$file")"
  else
    echo "$label"
  fi
}

extract_metric_value() {
  local file="$1"
  local key="$2"
  local line
  line="$(awk -v metric_key="$key" '
    index($0, "- " metric_key ":") == 1 {
      print $0
      exit
    }
  ' "$file")"
  if [[ -z "$line" ]]; then
    echo "n/a"
    return
  fi
  local prefix="- ${key}:"
  local value="${line#${prefix}}"
  echo "$value" \
    | sed -E 's/  \(formula:.*$//' \
    | sed -E 's/^ +| +$//g'
}

to_number() {
  local value="$1"
  if [[ "$value" == "n/a" ]]; then
    echo "n/a"
    return
  fi
  local cleaned="${value//,/}"
  cleaned="${cleaned%\%}"
  if awk -v v="$cleaned" 'BEGIN { exit !(v ~ /^[-+]?[0-9]*\.?[0-9]+$/) }'; then
    echo "$cleaned"
  else
    echo "n/a"
  fi
}

format_number() {
  local value="$1"
  awk -v v="$value" 'BEGIN { printf "%.2f", v }' | sed -E 's/\.00$//; s/([0-9])0$/\1/'
}

compute_delta() {
  local prev="$1"
  local curr="$2"
  if [[ "$prev" == "n/a" || "$curr" == "n/a" ]]; then
    echo "n/a"
    return
  fi
  local delta
  delta="$(awk -v p="$prev" -v c="$curr" 'BEGIN { printf "%.6f", (c - p) }')"
  local formatted
  formatted="$(format_number "$delta")"
  if [[ "$formatted" == "0" ]]; then
    echo "0"
  elif [[ "$formatted" == -* ]]; then
    echo "$formatted"
  else
    echo "+$formatted"
  fi
}

render_delta_line() {
  local metric="$1"
  local prev_display="$2"
  local curr_display="$3"
  local prev_number="$4"
  local curr_number="$5"
  local suffix="${6:-}"
  local delta
  delta="$(compute_delta "$prev_number" "$curr_number")"
  if [[ "$delta" == "n/a" ]]; then
    echo "| ${metric} | ${prev_display} | ${curr_display} | n/a |"
  else
    echo "| ${metric} | ${prev_display} | ${curr_display} | ${delta}${suffix} |"
  fi
}

if [[ -z "$label_prev" ]]; then
  label_prev="$(extract_heading_label "$previous_path")"
fi
if [[ -z "$label_current" ]]; then
  label_current="$(extract_heading_label "$current_path")"
fi

prev_mrr="$(extract_metric_value "$previous_path" "MRR")"
curr_mrr="$(extract_metric_value "$current_path" "MRR")"
prev_delivery_cost="$(extract_metric_value "$previous_path" "Delivery cost")"
curr_delivery_cost="$(extract_metric_value "$current_path" "Delivery cost")"
prev_acquisition_spend="$(extract_metric_value "$previous_path" "Acquisition spend")"
curr_acquisition_spend="$(extract_metric_value "$current_path" "Acquisition spend")"
prev_new_customers="$(extract_metric_value "$previous_path" "New customers")"
curr_new_customers="$(extract_metric_value "$current_path" "New customers")"
prev_margin="$(extract_metric_value "$previous_path" "Margin")"
curr_margin="$(extract_metric_value "$current_path" "Margin")"
prev_roi="$(extract_metric_value "$previous_path" "ROI")"
curr_roi="$(extract_metric_value "$current_path" "ROI")"
prev_cac="$(extract_metric_value "$previous_path" "CAC")"
curr_cac="$(extract_metric_value "$current_path" "CAC")"
prev_ltv="$(extract_metric_value "$previous_path" "LTV")"
curr_ltv="$(extract_metric_value "$current_path" "LTV")"
prev_ltv_cac="$(extract_metric_value "$previous_path" "LTV/CAC ratio")"
curr_ltv_cac="$(extract_metric_value "$current_path" "LTV/CAC ratio")"
prev_breakeven="$(extract_metric_value "$previous_path" "Break-even units")"
curr_breakeven="$(extract_metric_value "$current_path" "Break-even units")"

prev_mrr_num="$(to_number "$prev_mrr")"
curr_mrr_num="$(to_number "$curr_mrr")"
prev_delivery_cost_num="$(to_number "$prev_delivery_cost")"
curr_delivery_cost_num="$(to_number "$curr_delivery_cost")"
prev_acquisition_spend_num="$(to_number "$prev_acquisition_spend")"
curr_acquisition_spend_num="$(to_number "$curr_acquisition_spend")"
prev_new_customers_num="$(to_number "$prev_new_customers")"
curr_new_customers_num="$(to_number "$curr_new_customers")"
prev_margin_num="$(to_number "$prev_margin")"
curr_margin_num="$(to_number "$curr_margin")"
prev_roi_num="$(to_number "$prev_roi")"
curr_roi_num="$(to_number "$curr_roi")"
prev_cac_num="$(to_number "$prev_cac")"
curr_cac_num="$(to_number "$curr_cac")"
prev_ltv_num="$(to_number "$prev_ltv")"
curr_ltv_num="$(to_number "$curr_ltv")"
prev_ltv_cac_num="$(to_number "$prev_ltv_cac")"
curr_ltv_cac_num="$(to_number "$curr_ltv_cac")"
prev_breakeven_num="$(to_number "$prev_breakeven")"
curr_breakeven_num="$(to_number "$curr_breakeven")"

momentum_note="Mixed movement. Focus on one bottleneck metric this week."
if [[ "$prev_ltv_cac_num" != "n/a" && "$curr_ltv_cac_num" != "n/a" ]]; then
  if awk -v p="$prev_ltv_cac_num" -v c="$curr_ltv_cac_num" 'BEGIN { exit !(c > p && c >= 3) }'; then
    momentum_note="Unit economics improved: LTV/CAC is rising and above 3."
  elif awk -v c="$curr_ltv_cac_num" 'BEGIN { exit !(c < 3) }'; then
    momentum_note="Unit economics warning: LTV/CAC is below 3. Prioritize retention or CAC efficiency."
  fi
fi

cac_note="CAC trend unclear."
if [[ "$prev_cac_num" != "n/a" && "$curr_cac_num" != "n/a" ]]; then
  if awk -v p="$prev_cac_num" -v c="$curr_cac_num" 'BEGIN { exit !(c < p) }'; then
    cac_note="CAC improved (down week-over-week)."
  elif awk -v p="$prev_cac_num" -v c="$curr_cac_num" 'BEGIN { exit !(c > p) }'; then
    cac_note="CAC worsened (up week-over-week). Audit acquisition channels."
  else
    cac_note="CAC is flat week-over-week."
  fi
fi

mkdir -p "$(dirname "$output_path")"

{
  echo "# Founder Weekly Delta - ${label_prev} to ${label_current}"
  echo
  echo "| Metric | Previous | Current | Delta |"
  echo "|---|---:|---:|---:|"
  render_delta_line "MRR" "$prev_mrr" "$curr_mrr" "$prev_mrr_num" "$curr_mrr_num"
  render_delta_line "Delivery cost" "$prev_delivery_cost" "$curr_delivery_cost" "$prev_delivery_cost_num" "$curr_delivery_cost_num"
  render_delta_line "Acquisition spend" "$prev_acquisition_spend" "$curr_acquisition_spend" "$prev_acquisition_spend_num" "$curr_acquisition_spend_num"
  render_delta_line "New customers" "$prev_new_customers" "$curr_new_customers" "$prev_new_customers_num" "$curr_new_customers_num"
  render_delta_line "Margin" "$prev_margin" "$curr_margin" "$prev_margin_num" "$curr_margin_num" " pp"
  render_delta_line "ROI" "$prev_roi" "$curr_roi" "$prev_roi_num" "$curr_roi_num" " pp"
  render_delta_line "CAC" "$prev_cac" "$curr_cac" "$prev_cac_num" "$curr_cac_num"
  render_delta_line "LTV" "$prev_ltv" "$curr_ltv" "$prev_ltv_num" "$curr_ltv_num"
  render_delta_line "LTV/CAC ratio" "$prev_ltv_cac" "$curr_ltv_cac" "$prev_ltv_cac_num" "$curr_ltv_cac_num"
  render_delta_line "Break-even units" "$prev_breakeven" "$curr_breakeven" "$prev_breakeven_num" "$curr_breakeven_num"
  echo
  echo "## Signals"
  echo
  echo "- ${momentum_note}"
  echo "- ${cac_note}"
  echo "- Keep CAC and LTV directionally opposite (CAC down, LTV up) before scaling spend."
  echo
  echo "## Next Actions"
  echo
  echo "1. Re-check weakest metric in Commands."
  echo "2. Record one experiment to improve that metric this week."
  echo "3. Re-run this delta report next week."
} > "$output_path"

echo "Wrote founder weekly delta to: $output_path"
