import XCTest
@testable import FluidReader

final class FounderCommandPresetTests: XCTestCase {
    func testMarkdownIncludesCoreFormulasAndWorkflowCommands() {
        let markdown = FounderCommandPreset.markdown()

        XCTAssertTrue(markdown.contains("Fame command presets"))
        XCTAssertTrue(markdown.contains("roi 1200 1000"))
        XCTAssertTrue(markdown.contains("runway 240000 12000"))
        XCTAssertTrue(markdown.contains("run-fame-sprint"))
        XCTAssertTrue(markdown.contains("run-fame-sprint-snapshot"))
        XCTAssertTrue(markdown.contains("run-fame-next-move"))
        XCTAssertTrue(markdown.contains("run-fame-next-move-cadence-execution-kit"))
        XCTAssertTrue(markdown.contains("run-fame-next-move-copy-drafts"))
        XCTAssertTrue(markdown.contains("run-fame-morning-brief"))
        XCTAssertTrue(markdown.contains("run-fame-midday-brief"))
        XCTAssertTrue(markdown.contains("run-fame-evening-brief"))
        XCTAssertTrue(markdown.contains("run-fame-weekly-rollup"))
        XCTAssertTrue(markdown.contains("run-fame-24h-queue"))
        XCTAssertTrue(markdown.contains("run-fame-command-center"))
        XCTAssertTrue(markdown.contains("run-fame-breakthrough-forecast"))
        XCTAssertTrue(markdown.contains("run-fame-ops-bundle"))
        XCTAssertTrue(markdown.contains("run-fame-daily-checkpoint"))
        XCTAssertTrue(markdown.contains("run-fame-daily-scorecard"))
        XCTAssertTrue(markdown.contains("run-fame-escalation-nudge"))
        XCTAssertTrue(markdown.contains("run-fame-operator-dashboard"))
        XCTAssertTrue(markdown.contains("run-fame-narrative-lab"))
        XCTAssertTrue(markdown.contains("run-fame-spotlight-pack"))
        XCTAssertTrue(markdown.contains("run-fame-launch-day-script"))
        XCTAssertTrue(markdown.contains("run-fame-launch-countdown"))
        XCTAssertTrue(markdown.contains("run-fame-pulse-nudge"))
        XCTAssertTrue(markdown.contains("run-fame-recovery-checklist"))
        XCTAssertTrue(markdown.contains("run-fame-recovery-proof-pack"))
        XCTAssertTrue(markdown.contains("open-latest-command-center"))
        XCTAssertTrue(markdown.contains("open-latest-daily-checkpoint"))
        XCTAssertTrue(markdown.contains("open-latest-risk-timeline"))
        XCTAssertTrue(markdown.contains("open-latest-pulse-nudge"))
        XCTAssertTrue(markdown.contains("open-latest-daily-scorecard"))
        XCTAssertTrue(markdown.contains("open-latest-operator-dashboard"))
        XCTAssertTrue(markdown.contains("open-latest-narrative-lab"))
        XCTAssertTrue(markdown.contains("open-latest-spotlight-pack"))
        XCTAssertTrue(markdown.contains("open-latest-launch-day-script"))
        XCTAssertTrue(markdown.contains("open-latest-launch-countdown"))
        XCTAssertTrue(markdown.contains("open-latest-breakthrough-forecast"))
        XCTAssertTrue(markdown.contains("open-latest-morning-brief"))
        XCTAssertTrue(markdown.contains("open-latest-midday-brief"))
        XCTAssertTrue(markdown.contains("open-latest-evening-brief"))
        XCTAssertTrue(markdown.contains("open-latest-next-move-handoff"))
        XCTAssertTrue(markdown.contains("open-latest-next-move-draft-pack"))
        XCTAssertTrue(markdown.contains("copy-next-move-drafts"))
        XCTAssertTrue(markdown.contains("copy-next-move-launch-now-sequence"))
        XCTAssertTrue(markdown.contains("copy-next-move-cadence-execution-kit"))
        XCTAssertTrue(markdown.contains("copy-next-move-cadence-post-queue"))
        XCTAssertTrue(markdown.contains("copy-next-move-reply-ladder"))
        XCTAssertTrue(markdown.contains("copy-next-move-cadence-post"))
        XCTAssertTrue(markdown.contains("copy-next-move-x-draft"))
        XCTAssertTrue(markdown.contains("copy-next-move-bluesky-draft"))
        XCTAssertTrue(markdown.contains("copy-next-move-linkedin-draft"))
        XCTAssertTrue(markdown.contains("copy-next-move-cadence-step"))
        XCTAssertTrue(markdown.contains("open-latest-escalation-nudge"))
        XCTAssertTrue(markdown.contains("open-latest-recovery-checklist"))
        XCTAssertTrue(markdown.contains("open-latest-recovery-proof-pack"))
        XCTAssertTrue(markdown.contains("open-fame-snapshot-folder"))
        XCTAssertTrue(markdown.contains("copy-founder-command-presets"))
        XCTAssertTrue(markdown.contains("copy-launch-kit"))
        XCTAssertTrue(markdown.contains("copy-fame-sprint"))
        XCTAssertTrue(markdown.contains("copy-fame-pack"))
        XCTAssertTrue(markdown.contains("copy-experiment-board"))
        XCTAssertTrue(markdown.contains("zsh scripts/check_growth.sh"))
    }

    func testMarkdownUsesChannelOverridesForLaunchCommand() {
        let markdown = FounderCommandPreset.markdown(
            primaryChannel: "YouTube",
            backupChannel: "Podcast"
        )
        XCTAssertTrue(markdown.contains(#"--primary-channel "YouTube" --backup-channel "Podcast""#))
    }
}
